# Writes the wrapper through which test_pn_all compiles one suite. The build
# runs it (tests/CMakeLists.txt) whenever the suite or this script changes:
#
#   cmake -DSUITE=<tests/test_pn_X.cpp, absolute> -DOUT=<wrapper .cpp> -P WrapSuite.cmake
#
# The wrapper is, in order:
#   1. the suite's own #include lines, in the suite's order, at global scope.
#      Every header the suite names is then already in (#pragma once, include
#      guards) when the suite itself is included below, inside a namespace, so
#      no standard, engine or port header ever lands inside that namespace;
#   2. the suite, #included inside namespace PnSuites::<name>. Its main() and
#      its helpers (Same, Trace, struct Run, testSettings...) are then its own:
#      two suites' `struct Run` with inline members would otherwise be one
#      symbol to the linker, which keeps either body without a word;
#   3. a registration, through which the runner (RunAll.cpp) finds the suite.
#
# main() keeps its name. A function called main outside the global namespace
# is an ordinary function (C++20 [basic.start.main]/3), so no macro renames it
# and nothing else in the suite can be renamed by accident.
#
# Two things cannot be hoisted faithfully, and each is decided here rather than
# left to surprise the compiler: a quoted #include of a file beside the suite
# (the compiler looks beside the INCLUDING file first, and the wrapper does not
# live in tests/) is written as that file's absolute path; an #include inside
# an #if would be included unconditionally, so it stops the build with the
# reason.

foreach(_var SUITE OUT)
    if (NOT DEFINED ${_var})
        message(FATAL_ERROR "WrapSuite.cmake: -D${_var}=... is required")
    endif()
endforeach()

get_filename_component(_suitePath "${SUITE}" ABSOLUTE)
get_filename_component(_suiteDir "${_suitePath}" DIRECTORY)
get_filename_component(_name "${_suitePath}" NAME_WE)
if (NOT EXISTS "${_suitePath}")
    message(FATAL_ERROR "WrapSuite.cmake: ${_suitePath} does not exist")
endif()
if (NOT _name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "WrapSuite.cmake: '${_name}' is not a C++ identifier, so it cannot name the namespace "
                        "${_suitePath} is wrapped in")
endif()

# Only the directives that matter: the includes, and the conditionals around
# them. Longer alternatives first, so `#ifdef` is not read as `#if`.
file(STRINGS "${_suitePath}" _directives REGEX "^[ \t]*#[ \t]*(ifndef|ifdef|include|endif|if)([^A-Za-z0-9_]|$)")

set(_depth 0)
set(_includes "")
foreach(_line IN LISTS _directives)
    string(REGEX MATCH "^[ \t]*#[ \t]*([a-z]+)" _unused "${_line}")
    set(_keyword "${CMAKE_MATCH_1}")
    if (_keyword STREQUAL "include")
        if (_depth GREATER 0)
            message(FATAL_ERROR "WrapSuite.cmake: ${_suitePath} includes a header inside an #if:\n"
                                "  ${_line}\n"
                                "test_pn_all hoists a suite's includes to global scope unconditionally. Include "
                                "the header unconditionally, or move the #if inside the header.")
        endif()
        # Two steps: ${CMAKE_MATCH_1} in the same if() would be expanded before
        # MATCHES sets it.
        set(_beside "")
        if (_line MATCHES "^[ \t]*#[ \t]*include[ \t]*\"([^\"]+)\"")
            if (EXISTS "${_suiteDir}/${CMAKE_MATCH_1}" AND NOT IS_DIRECTORY "${_suiteDir}/${CMAKE_MATCH_1}")
                get_filename_component(_beside "${_suiteDir}/${CMAKE_MATCH_1}" ABSOLUTE)
            endif()
        endif()
        if (_beside)
            string(APPEND _includes "#include \"${_beside}\"\n")
        else()
            string(STRIP "${_line}" _line)
            string(APPEND _includes "${_line}\n")
        endif()
    elseif (_keyword MATCHES "^if")
        math(EXPR _depth "${_depth} + 1")
    elseif (_keyword STREQUAL "endif")
        math(EXPR _depth "${_depth} - 1")
    endif()
endforeach()

set(_registry "${CMAKE_CURRENT_LIST_DIR}/SuiteRegistry.hpp")
file(WRITE "${OUT}"
"// Generated by tests/all/WrapSuite.cmake from ${_suitePath}.
// Do not edit: the build rewrites it whenever the suite changes.

#include \"${_registry}\"

// ${_name}'s own includes, at global scope.
${_includes}
namespace PnSuites::${_name} {
#include \"${_suitePath}\"
} // namespace PnSuites::${_name}

static const PnAll::Registration kRegistration{\"${_name}\", &PnSuites::${_name}::main};
")
